<div class="content">
    <h1><a href="/icinga/">Icinga Dashboard</a></h1>
    <div style="float:right; border:1px solid gray; margin:5px;padding:5px;">
        <h2>legend</h2>
        <div class="box legend ok" >ok</div>
        <div class="box legend warning" >warning</div>
        <div class="box legend critical" >critical</div>
        <div class="box legend unknown" >unknown</div>
        <br>
        <div class="box legend ok-ack" >Acknowledged:</div>
        <div class="box legend warning-ack" >warning</div>
        <div class="box legend critical-ack" >critical</div>
        <div class="box legend unknown-ack" >unknown</div>
        <br>
        <div class="box legendtext">H = Host Acknowledged</div>    
        <div class="box legendtext">&#8730;= Service Acknowledged</div>
    </div>

    <h1><a href="/icinga/">Icinga Dashboard</a></h1>


<br clear='all'/><h2>Service Info</h2>


    <h1>Boxy Dashboard!</h1>

<?= $this->url ?>


</div>
